name: Gitlab Mirroring

on:
  push:
    branches:
      - main
      - dev
  delete:

jobs:
  gitlab-mirroring:
    name: Gitlab Mirroring
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: git@gitlab.com:koudmain/koudmain-workspace.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
