name: "Global Checks & Automation"

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  call-add-to-project:
    name: "Auto Configure Project"
    if: github.event.action == 'opened'
    uses: Koudmain/.github/.github/workflows/auto-add-project.yml@main
    secrets:
      ORG_PAT: ${{ secrets.ORG_PAT }}

  call-verify-issue:
    name: "Verify Linked Issue"
    if: github.event_name == 'pull_request'
    uses: Koudmain/.github/.github/workflows/pr-verify-linked-issue.yml@main
    secrets:
      ORG_PAT: ${{ secrets.ORG_PAT }}

  call-require-checklist:
    name: "Require Checklist"
    if: github.event_name == 'pull_request'
    uses: Koudmain/.github/.github/workflows/pr-require-checklist.yml@main
